apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: quay.io/amorgant/server-debug
    custom:
      # environment variable $IMG2 set to the built image2
      buildCommand: make build
    context: .
deploy:
  kubectl:
    manifests:
    - k8s/*
