apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
     sha256: {}
  artifacts:
  - image: quay.io/amorgant/server-debug
    docker:
      dockerfile: docker/debug/Dockerfile
    context: .
deploy:
  kubectl:
    manifests:
      - k8s/*